# Generated by Django 5.1.3 on 2024-12-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="token",
            field=models.CharField(default=1, max_length=50, verbose_name="token"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="payments.gateway",
                verbose_name="gateway",
            ),
        ),
    ]
