# Generated by Django 5.1.3 on 2024-12-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_file_file_type_alter_file_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "audio"), (2, "video"), (3, "pdf")],
                verbose_name="file type",
            ),
        ),
    ]
